version: "3.9"
services:
    web: 
        build: .
        volumes:
          - ./backend:/app
        ports:
          - "8000:8000"
        links:
          - "mongo"
    mongo:
        image: "mongo"
        ports:
          - 27018:27017

